FORMAT: 1A
HOST: https://localhost:3333

# BoxVendas API

API de fluxo de dados e processamento de compras.

# Group API

## Sobre [/]

Receber requisições e enviar dados para uma pagina web BoxVendas,
processar os dados de cadastro, compras entre outros de diversos clientes e vendedores.
Gerênciar banco de dados relacional e conexão entre clientes, vendedores e produtos,
calcular endereço. Api é desenvolvida em Typescript e executada em NodeJS.

# Group Product

## Listar todos os Produtos [/product/list]

### Listar Todos [GET]

+ Response 200 (aplication/json)
    + Attributes (array[Product])

## Listar produtos de um vendedor [/product/salesman/{id}]

+ Parameters
    + id: 1 (number, required) -  ID do vendedor

### Listar por vendedor [GET]

+ Response 200 (aplication/json)
    + Attributes (array[Product])

+ Response 406 (aplication/json)
    + Attributes (Error)

## Listar um produto [/product/list/{id}]

+ Parameters
    + id: 1 (number, required) -  Id do produto

### Listar um [GET]

+ Response 200 (aplication/json)
    + Attributes (Product)

+ Response 406 (aplication/json)
    + Attributes (Error)

## Listar produtos em destaque [/product/list/highlighted]

### Listar destaques [GET]

+ Response 200 (aplication/json)
    + Attributes (array[Product])

## Cadastrar Produtos [/product/register]

### Cadastrar [POST]

+ Request Cadastrar um produto no banco de dados
    + Attributes (ProductUnr)

+ Response 201 (aplication/json)
    + Attributes (Product)

+ Response 406 (aplication/json)
    + Attributes (Error)

## Modificar um produto [/product/update/{id}]

+ Parameters
    + id: 1 (number, required) -  Id do produto

### Modificar [PUT]

+ Request Modificar dados do usuario
    + Attributes (ProductUnr)

+ Response 200 (aplication/json)
    + Attributes (Product)

+ Response 406 (aplication/json)
    + Attributes (Error)

## Deletar Produto [/product/delete/{id}]

+ Parameters
    + id: 1 (number, required) -  Id do produto

### Deletar [DELETE]

+ Response 204 (No-Content)

+ Response 406 (aplication/json)
    + Attributes (Error)

# Group User

## Listar Usuarios [/user/list]

### Listar Todos [GET]

+ Response 200 (aplication/json)
    + Attributes (array[User])

+ Response 404 (aplication/json)
    + Attributes (Error)

+ Response 400 (aplication/json)
    + Attributes (Error)

## Listar um usuario [/user/list/{id}]

+ Parameters
    + id: 1 (number, required) - Id do usuario

### Listar um [GET]

+ Response 200 (aplication/json)
    + Attributes (User)

+ Response 404 (aplication/json)
    + Attributes (Error)

+ Response 400 (aplication/json)
    + Attributes (Error)

## Cadastrar usuario [/user/register]

### Cadastrar [POST]

+ Request Cadastrar um usuario no banco de dados
    + Attributes (UserUnr)

+ Response 201 (aplication/json)
    + Attributes (User)

+ Response 406 (aplication/json)
    + Attributes (Error)

## Modificar dados do usuario [/user/update/{id}]

+ Parameters
    + id: 1 (number, required) -  Id do usuario

### Modificar [PUT]

+ Request Modificar dados do usuario
    + Attributes (User)

+ Response 200 (aplication/json)
    + Attributes (User)

+ Response 404 (aplication/json)
    + Attributes (Error)

+ Response 400 (aplication/json)
    + Attributes (Error)

## Deletar usuario [/user/delete/{id}]

+ Parameters
    + id: 1 (number, required) -  Id do usuario

### Deletar [DELETE]

+ Response 204 (No-Content)

+ Response 404 (aplication/json)
    + Attributes (Error)

# Group Salesman

## Listar Vendedores [/salesman/list]

### Listar Todos [GET]

+ Response 200 (aplication/json)
    + Attributes (array[Salesman])

+ Response 400 (aplication/json)
    + Attributes (Error)

## Listar um vendedor [/salesman/list/{id}]

+ Parameters
    + id: 1 (number, required) -  Id do vendedor

### Listar um [GET]

+ Response 200 (aplication/)
    + Attributes (Salesman)

+ Response 400 (aplication/json)
    + Attributes (Error)

## Cadastrar um vendedor [/salesman/register]

### Cadastrar [POST]

+ Request Cadastrar vendedor no banco de dados
    + Attributes (SalesmanUnr)

+ Response 200 (aplication/json)
    + Attributes (Salesman)

+ Response 400 (aplication/json)
    + Attributes (Error)

## Modificar dados do vendedor [/salesman/update/{id}]

+ Parameters
    + id: 1 (number, required) -  Id do Vendedor

### Modificar [PUT]

+ Request Modificar dados do vendedor no banco de dados
    + Attributes (SalesmanUnr)

+ Response 200 (aplication/json)
    + Attributes (Salesman)

+ Response 404 (aplication/json)
    + Attributes (Error)

+ Response 400 (aplication/json)
    + Attributes (Error)

## Deletar um vendedor [/salesman/delete/{id}]

+ Parameters
    + id: 1 (number, required) - Id do vendedor

### Deletar [DELETE]

+ Response 204 (No-Content)

+ Response 404 (aplication/json)
    + Attributes (Error)

# Group Transactions

## Efetuar um pedido [/transaction/purchase]

### Criar pedido [POST]

+ Request cadastrar pedido no banco de dados
    + Attributes (PurchaseUnr)

+ Response 202 (aplication/json)
    + Attributes (Purchase)

+ Response 404 (aplication/json)
    + Attributes (Error)

+ Response 400 (aplication/json)
    + Attributes (Error)

# Data Structures

## Product (ProductUnr)
+ id: 1 (number, required) - Id do produto
+ stars (array[number]) - Avaliações do produto

## ProductUnr (object)
+ name (string) - Nome do produto
+ imageURL (array[string]) - Uma ou mais imagens do produto
+ description (string) - Descrição
+ value (string) - Valor
+ salesmanId (number) - Id do vendedor
+ stock (number) - Quantidade disponíveis em estoque

## User (UserUnr)
+ id: 1 (number, required) - Id do usuario
+ birth date (string) -  Data de nascimento do usuario
+ cpf (string) - CPF do usuario
+ cellphone (string) - Telefone do usuario
+ address (array[Address]) - Um ou mais endereços do usuario
+ purchase (array[Purchase]) - Pedidos do usuario
+ cart (array[Product]) - Carrinho do usuario

## UserUnr (object)
+ name (string) - Nome do usuario
+ email (string, required) - Email do usuario
+ password (string, required) - Password doSenha do usuario
+ register date (string) - Data de cadastro do usuario

## Salesman (SalesmanUnr)
+ id: 1 (number, required) - Id do vendedor

## SalesmanUnr (object)
+ name (string) - Nome do vendedor
+ email (string, required) - Email do vendedor
+ password (string, required) - Password do vendedor
+ cellphone (string) - Telefone do vendedor
+ address (array[Address]) - Endereço do vendedor
+ cpf (string) - CPF do vendedor
+ sales (array[Sale]) - Vendas do vendedor

## Purchase (PurchaseUnr)
+ payment (object) - Comprovante de pagamento
+ send (object) - Comprovante de envio
+ receivement (object) - Comprovanre de recebimento
+ tracking code (string) - Código de rastreio

## PurchaseUnr (object)
+ userId: 1 (number, required) - Id do usuario
+ salesmanId: 1 (number, required) - Id do vendedor
+ uniqValue (number) - Valor unitario
+ freightValue (number) - Valor do frete
+ totalValue (number) - Valor total
+ address (Address) - Endereço de entrega
+ method (number) - Metodo de pagamento

## Address (object)
+ street (string) - Rua
+ number (number) - Numero
+ district (string) - Bairro
+ city (string) - Cidade
+ uf (string) - UF
+ cep (number) -  CEP

## Sale (object)
+ sale (object) - Comprovante de venda
+ send (object) - Comprovante de envio

## Error (object)
+ code: 400 (number) - Status code
+ message: Error (string) - Mensagem do status
